version: '3'

vars:
  BIN_DIR: bin
  GAMEOFLIFE_DIR: gameoflife
  LANGTONSANT_DIR: langtons-ant
  CELLULARAUTOMATA_DIR: cellular-automata
  WIREWORLD_DIR: wireworld
  BRIANSBRAIN_DIR: brians-brain

tasks:
  gameoflife:build:
    desc: Build Conway's Game of Life
    dir: "{{.GAMEOFLIFE_DIR}}"
    cmds:
      - go build -o ../{{.BIN_DIR}}/gameoflife{{exeExt}} ./cmd/app

  gameoflife:run:
    desc: Executes Conway's Game of Life
    dir: "{{.GAMEOFLIFE_DIR}}"
    cmds:
      - go run ./cmd/app

  gameoflife:tidy:
    desc: go mod tidy no Game of Life
    dir: "{{.GAMEOFLIFE_DIR}}"
    cmds:
      - go mod tidy

  langtons-ant:build:
    desc: Build Langton's Ant
    dir: "{{.LANGTONSANT_DIR}}"
    cmds:
      - go build -o ../{{.BIN_DIR}}/langtonsant{{exeExt}} ./cmd/langtonsant
  
  langtons-ant:run:
    desc: Executes Langton's Ant
    dir: "{{.LANGTONSANT_DIR}}"
    cmds:
      - go run ./cmd/langtonsant

  cellular-automata:build:
    desc: Build Elementary Cellular Automata
    dir: "{{.CELLULARAUTOMATA_DIR}}"
    cmds:
      - go build -o ../{{.BIN_DIR}}/cellularautomata{{exeExt}} ./cmd/cellularautomata
  
  cellular-automata:run:
    desc: Executes Elementary Cellular Automata
    dir: "{{.CELLULARAUTOMATA_DIR}}"
    cmds:
      - go run ./cmd/cellularautomata

  wireworld:build:
    desc: Build Wireworld
    dir: "{{.WIREWORLD_DIR}}"
    cmds:
      - go build -o ../{{.BIN_DIR}}/wireworld{{exeExt}} ./cmd/wireworld

  wireworld:run:
    desc: Executes Wireworld
    dir: "{{.WIREWORLD_DIR}}"
    cmds:
      - go run ./cmd/wireworld

  brians-brain:build:
    desc: Build Brian's Brain
    dir: "{{.BRIANSBRAIN_DIR}}"
    cmds:
      - go build -o ../{{.BIN_DIR}}/briansbrain{{exeExt}} ./cmd/briansbrain
  
  brians-brain:run:
    desc: Executes Brian's Brain
    dir: "{{.BRIANSBRAIN_DIR}}"
    cmds:
      - go run ./cmd/brians-brain